spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    cloud:
    config:
      enabled: false    # 테스트 시 Config Server 비활성화
    discovery:
      enabled: false    # 테스트 시 Service Discovery 비활성화
jwt:
  secret: testSecretKeyForJwtTokenGenerationInTestEnvironmentMustBeLongEnough
  access-token-validity: 3600000
  refresh-token-validity: 86400000
eureka:
  client:
    enabled: false     # 테스트 시 Eureka Client 비활성화