spring:
  application:
    name: member-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.autoconfigure: DEBUG